from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]

D={
# Chapter 1
'为什么不能直接精排全库？':'因为精排通常包含大量稀疏特征读取、交叉网络和序列交互，单 item 成本乘上亿级库存后远超在线 SLA。分层把问题从“全库精确打分”改成“高召回候选生成 + 小集合高精度排序”，本质是计算复杂度与可恢复截断误差的权衡。',
'召回和排序分别看什么离线指标？':'召回优先看 Recall@K、HitRate、coverage、route marginal recall，并拆 exact/index/end-to-end；排序看 AUC/GAUC、NDCG、logloss/calibration 和关键 cohort。两者都必须最终连接到线上业务指标，不能拿 AUC 评价 ANN 索引，也不能只拿 Recall 评价最终列表。',
'哪个阶段最容易造成线上 latency 尖峰？':'没有固定答案，常见 tail 来自远程 feature fetch、ANN 热点 shard、长序列交互和重排外部依赖。应通过分布式 trace 做 per-stage P99 分解；“平均最慢”的 stage 不一定是“尾延迟贡献最大”的 stage。',
'如果线上特征服务慢 15ms，你优先从哪里降延迟？':'先确认 15ms 是平均还是 P99、由网络/缓存/计算哪部分构成。优先做 feature locality、batch/get 合并、cache、预计算和删低价值远程特征；只有确认模型计算是瓶颈后才做量化/蒸馏。',
'如何保证模型、特征、ANN 索引版本原子切换？':'使用 immutable version 和兼容性 manifest，把 model、feature schema、embedding/index 绑定成一个 release bundle；新版本后台 warmup 与 sanity check 后通过配置原子切流。保留旧 bundle 与双读/影子验证，任何异常可秒级 rollback。',
'粗排为什么越来越重要？':'候选量和精排复杂度同步增长时，粗排承担“以很低成本保留精排 Top 候选”的任务，决定了复杂精排是否有 ROI。优秀粗排更关注 top-preservation/oracle recall 与 latency，而不是单纯复制精排 AUC。',
'重排如何处理多个业务目标？':'先把精排各目标转成可比较的 utility 或约束，再做列表级优化，例如加权、多样性惩罚、quota、DPP/MMR 或约束搜索。业务硬约束与软目标应分开：安全/库存是 gate，CTR/时长/多样性更适合做 Pareto 权衡。',
'阶段之间是否应该共享模型？':'可以共享底层 embedding、teacher signal 或特征，但不应默认同一网络直接复用。召回需要可索引性、粗排重成本效率、精排重表达力，目标和输入分布不同；更常见是蒸馏/共享表征而非完全同构。',
'多路候选如何去重和融合？':'先按 item_id 去重并保留 route provenance、各路原始分/排名；再用固定 quota、归一化分数、learned mixer 或后续粗排融合。必须记录重叠率和 marginal recall，否则某一路可能只是在复制已有候选。',
'某一路 Recall 高但上线无收益怎么办？':'先看它命中的正例是否已经被其他路覆盖，以及新增候选是否能进入最终 TopK；再看该路带来的 item 分布是否被粗排/精排系统性压掉。用 remove-one-route / add-one-route 实验测 marginal gain，而不是看单路 Recall。',
'用户兴趣很窄时是否还需要多路？':'仍可能需要，但应降低冗余并提高与主兴趣相关的高精度路权重。多路的意义还包括新鲜度、探索和供给覆盖；可用用户兴趣熵/历史长度做 dynamic routing，而不是所有用户固定 quota。',
'如何用 learned routing 动态分配各召回路 quota？':'用用户状态、场景、历史长度、route 历史命中/成本作为输入，预测每一路的边际价值或 quota；训练可用下游点击/精排 teacher 或 bandit reward。上线必须设每路最小/最大配额和 fallback，避免 router collapse。',
'候选重叠很高时应该删一路还是保留冗余？':'先看重叠候选的质量、稳定性和故障隔离价值。若同样候选由完全相同数据/模型产生，通常应精简；若一路是低成本 fallback 或在特定 cohort 有独立增量，保留冗余可能提升可用性。',
'多目标权重怎么定？':'不要只在训练 loss 上拍权重。先明确业务 primary/guardrail，再通过离线 Pareto、score calibration、在线小流量实验调整；有时模型内 loss weight 与最终排序 utility weight应分开优化。',
'CTR 上升而时长下降怎么办？':'先做内容类型、用户 cohort、位置和 session 深度 slice，判断是否 clickbait 或“更高效完成任务”。如果时长是 guardrail 且显著恶化，应暂停放量；若次留/满意度上升，则需要重新审视时长是否仍是合适代理。',
'长期留存无法快速得到 label 怎么办？':'使用短期代理指标、多时间窗 survival/retention model、蒸馏或 uplift surrogate，但必须用周期性长期实验验证代理相关性。不要把短期 proxy 当成永久真目标，应维护 proxy→long-term 的相关性 dashboard。',
'视频长度偏差怎么处理？':'显式加入 duration、按长度分桶评估，并联合建模 watch time、completion ratio、有效播放等。完播率天然偏爱短视频，纯 watch time 又偏长视频，因此通常需要多目标或长度归一化而不是单一 label。',
'新作者如何保量？':'新作者/内容先过质量与安全 gate，再给受控 exploration quota；quota 随证据积累按后验质量衰减或毕业。评估既看短期接受率，也看供给留存和作者生态，避免无条件补贴。',
'如何防止推荐越来越窄？':'从召回多路覆盖、重排 diversity、新主题探索和长期目标四层治理，并监控用户级主题熵、重复率和 catalog coverage。关键是相关性下界内探索，而不是随机塞内容。',
'如果主指标不显著但多个代理指标都涨怎么办？':'按预注册规则解释：primary 不显著时不能因为 secondary 多个上涨就宣布成功，尤其存在多重检验。可延长到预定样本量、看 effect CI 和代理到长期目标的历史相关性，必要时作为“有方向但证据不足”进入下一轮实验。',
'如何设计护栏指标？':'选择“绝不能为了主指标牺牲”的维度，如负反馈、崩溃/延迟、退款、安全、留存。护栏应定义容忍阈值和触发动作，而不仅是展示在 dashboard；还要避免与 primary 高度重复导致决策失去区分度。',
'生态指标怎么进入实验决策？':'将供给集中度、创作者留存、长尾曝光、内容质量等作为 secondary/guardrail，并设置更长观测窗口。若生态影响有明显网络外部性，普通 user-level A/B 可能低估，应考虑 cluster/market-level 试验或长期 holdout。',
'用户分层和多任务/多域建模有什么关系？':'分层是显式把异质人群拆开；多域/多任务是让模型共享部分参数同时学习差异。样本量足够且机制明显不同可显式分层，差异连续且共享价值高时更适合 domain-aware gate/experts。',
'如何验证分层有效？':'先证明不同层存在稳定的响应异质性，再比较“统一模型+segment feature”与“分层策略/模型”的增量。线上看各层 lift 与 overall 加权收益，同时监控边界用户频繁迁移和样本稀疏问题。',
'新老用户是否应该完全两套模型？':'通常不必完全割裂。可以共享 item/content encoder 和部分底层参数，新用户走 context/content/exploration 分支，历史积累后逐步提高序列/协同信号权重；这样减少切换 discontinuity 和维护成本。',
'搜索相关性和 CTR 冲突怎么办？':'搜索先保证 relevance 下界，再在相关候选内个性化优化 CTR/CVR；可把 relevance 设硬约束或高权重目标。不能为了 CTR 把不相关但诱导点击的结果排上来，否则会伤长期搜索信任。',
'能否用同一个双塔服务搜索和推荐？':'可以共享 item tower/semantic space，但 user/query tower 与训练样本通常不同。可做 multi-domain two-tower 或共享底座+场景 head，并分别校准与建索引；是否合并取决于语义空间一致性和线上成本。',
'Query Rewrite 对推荐有何对应物？':'推荐中对应的是 intent expansion / user-state rewrite：把短期行为、上下文或自然语言画像转成多个可检索意图，例如多兴趣 query vectors、semantic profile 或 session intent。',
'如何判断是流量季节性还是系统故障？':'对比历史同星期/节假日、外部活动与 control baseline，再看故障是否与版本、地域、端、feature freshness、错误率同步。季节性通常跨模型一致且平滑，系统故障常与某版本/链路突变高度相关。',
'哪些监控应该预先建设？':'至少有流量/曝光、candidate count、route overlap、feature missing/freshness、score distribution、各 stage P50/P99、timeout/fallback、业务 primary/guardrail，并能按 model/index/app/region/user cohort slice。',
'分数分布正常但 CTR 掉了说明什么？':'说明模型 raw score 本身未明显漂移，但展示环境、候选组成、位置、UI、埋点或用户流量可能变了。继续查 candidate overlap、position distribution、曝光日志、客户端版本和 calibration by slice。',
'只有 iOS CTR 跌、Android 正常，你下一步查什么？':'优先查 iOS app/version 发布、埋点、UI/位置、网络/feature 请求、设备特征默认值和实验覆盖；再对比同模型下候选与 score 分布。端特异退化通常先从客户端/流量差异排，而不是重训全局模型。',
'如果 AUC 正常但线上 CTR 跌，最可能是哪几类问题？':'候选分布/流量变了、train-serving skew、score calibration/阈值、位置/展示变化、延迟超时回退、策略覆盖或日志问题都可能。AUC 只说明离线排序能力，不验证线上数据和决策链。',
'提升来自模型还是数据？':'做正交 ablation：固定数据换模型、固定模型换数据，再测试交互项；同时保持训练步数、特征版本和 evaluation split 一致。若只有“数据+模型”同时变化才涨，应明确存在 interaction，不能把收益单归因模型。',
'为什么离线涨线上不涨？':'逐层排查 offline-online gap：候选/流量分布、特征 point-in-time、校准、延迟/超时、策略覆盖和实验功效。最有价值的是建立历史模型的 offline delta vs online lift scatter，知道哪些离线指标真正有预测力。',
'如何用 ablation 证明每个改动的增量价值？':'从同一 baseline 出发逐项 add-one/remove-one，并测试关键交互组合；报告 delta metric、置信区间、成本和 cohort。若多个改动强交互，应使用 factorial/小型组合实验而非把顺序增益当独立贡献。',
'如何证明短期提升没有牺牲长期价值？':'设置长期 holdout 或至少跨周观察 retention、负反馈、内容生态与复访；建立短期 proxy 与长期指标相关性。对可能有 novelty effect 的改动，不应只看首日/首周 uplift。',

# Chapter 2
'热门 Item 会不会和所有 Item 都相似？':'会产生这种偏置，因为热门 item 与很多用户共现。可用 IUF/用户活跃度降权、item popularity normalization、BM25-style 共现或 PMI 修正；同时按热门度 bucket 检查邻居语义纯度。',
'如何加入时间衰减？':'对共现贡献乘 exp(-Δt/τ) 或分段衰减，τ 对应业务兴趣半衰期；也可对用户行为时间与 item 共现时间分别处理。τ 应通过回放数据和不同品类 slice 调整，耐用品与新闻的最佳半衰期差异很大。',
'ItemCF 与矩阵分解有什么关系？':'二者都利用协同信号；ItemCF 显式基于局部共现邻接，MF 用低秩潜变量全局平滑交互矩阵。可把 MF item embedding 的近邻看成一种学习式 ItemCF，但其相似度由全局目标决定。',
'如何做离线更新与增量更新？':'主共现矩阵/邻接可日级全量重算，流式事件维护增量计数或 delta neighbor table；查询时主表+delta 合并。需要时间衰减、去重和周期 compact，防止增量表无限膨胀。',
'低频 Item 相似度如何平滑？':'用最小共现阈值、shrinkage/Bayesian prior、popular-normalized denominator 或退回 content embedding。低频 pair 的相似度高可能只是一次偶然共现，必须同时看 support。',
'共现窗口怎么选？':'按 session/时间窗/行为距离定义，越大覆盖多但噪声高。建议根据业务意图半衰期做 sweep，并区分购买链路和内容消费；还可对距离使用衰减而不是硬窗口。',
'隐式反馈如何训练 MF？':'常见 weighted implicit MF：把点击/购买映射 preference p_ui∈{0,1}，用 confidence c_ui 加权平方误差；或用 BPR 从正例和采样负例优化 pairwise ranking。核心是未观察不等于明确负例。',
'为什么 BPR 比 MSE 更适合排序？':'BPR 直接优化 s(u,i+) > s(u,i-) 的 pairwise 概率，更贴近隐式反馈的相对偏好；MSE 需要给未观察项设数值目标且重 calibration。BPR 代价是 pair sampling 设计会显著影响训练。',
'MF 与双塔的本质联系？':'经典 MF 可视为最简单双塔：user_id/item_id 查 embedding，score 是点积。现代双塔把 ID embedding 扩展为含上下文、文本、序列的 encoder，但仍保留分离编码和可索引点积这一核心约束。',
'双塔为什么表达能力弱？':'因为 user/item 在点积前独立编码，缺少 candidate-conditioned cross features；单个向量还可能压缩多兴趣。其优势“可预计算/可 ANN”与缺点“late interaction”是同一结构的两面。',
'怎么让双塔建模上下文？':'把时间、地域、设备、session intent 等加入 user/query tower；item tower 只放可预计算或慢变特征。若某上下文同时影响 item 表示，可用多版本 index、context-conditioned projection 或放到后续排序。',
'多兴趣向量怎么索引？':'每用户生成 M 个 interest query vectors，各自 ANN TopK 后 merge/dedup；M 可固定或动态。要防某个兴趣向量吞掉 quota，可按 interest weight 分配 K 并记录每个 interest 的边际召回。',
'怎样蒸馏精排信息到召回？':'用精排 teacher 给 user-item pair 产生 soft score/pairwise preference 或难负例，双塔 student 用 KL、MSE-on-logit、pairwise/contrastive loss 学习；同时保持 student 的 dot-product 可索引结构。重点验证召回 Recall 与 candidate distribution，而非只拟合 teacher score。',
'双塔召回分数如何校准？':'召回 dot product 通常首先是相对相似度，不天然是 CTR 概率。若需要跨路融合，可按 route 做 temperature/Platt/isotonic 或 learned mixer 校准；更稳的是把 route score/rank 交给粗排统一融合。',
'多正例 loss 怎么写？':'把同一 user 的多个真实正例都放入 numerator，例如 -log(Σ_{p∈P} exp(s_p/τ) / Σ_{a∈P∪N} exp(s_a/τ))，或对每个正例分别求 supervised contrastive loss。要 mask 同 item 重复，避免一个正例同时出现在 denominator 的负位置。',
'如何在线挖 hard negative？':'常见做法是周期性用当前/teacher 模型检索高分未交互候选，写入 hard-negative pool；训练时与 random/exposure negatives 混合。必须延迟刷新或版本化，避免在线模型错误立即自强化。',
'负采样比例怎么定？':'看梯度信息与成本而非固定 1:10。逐步增加 negatives，画 Recall/GAUC vs train cost 曲线，同时看 false-negative rate、hardness 分布；大 batch 时“比例”还受 in-batch 实际负例数影响。',
'曝光未点击和随机负例如何混合？':'曝光未点击更接近线上竞争但有 position/examination bias，随机负例覆盖广但太容易。可设 mixture，例如大部分曝光/检索 hard negatives + 一部分 random，分别加权并记录来源特征。',
'如何定义有效曝光？':'至少要满足 item 真正进入可视区域/停留达到阈值，而不只是服务端下发。定义依 UI：可结合 viewport、position、scroll、dwell 和渲染成功日志；有效曝光口径必须离线线上一致。',
'负反馈 label 权重怎么设计？':'显式“不感兴趣/举报”通常权重大于未点击，但不同负反馈语义不同。可按后续留存/恢复率标定权重，并设上限防极少数强负反馈梯度主导。',
'位置偏差如何估 propensity？':'最可靠来自小流量随机化/position swap；也可用 PBM/click model 估 examine probability。IPS 使用前检查 positivity 和权重尾部，极小 propensity 需 clipping/SNIPS/DR。',
'为什么 cosine 模型常需要归一化？':'cosine 定义就是方向相似度，L2 normalize 后 dot product 等于 cosine，能防向量 norm 无限制增大并利于统一 ANN 几何。但若 norm 本身编码置信度/热门度，归一化会丢信息，应通过实验决定。',
'什么时候应该做 popularity debias？':'当 embedding norm、曝光或推荐份额与 popularity 高度耦合，且长尾/个性化用户显著受损时。去偏应看用户效用和供给质量，不是为了“均匀”；热门本身若真实高质，过度惩罚也会伤体验。',
'长尾采样比例怎么验证？':'按 item popularity decile 分桶看 recall、precision、曝光和在线 lift，做不同 mixture ratio 的 Pareto curve。还要看总体质量是否被大量低质长尾拖累，并监控 tail item 的样本 support。',
'embedding 表怎么做量化？':'可用 FP16/BF16、INT8 per-row/per-channel scale、product quantization 或混合精度；训练/serving 分别决定。评估必须覆盖重构误差、下游 AUC/Recall、ANN topK 稳定性、内存带宽和实际 latency。',
'维度过大有什么线上征兆？':'内存/显存和网络带宽上升、embedding lookup 成为 P99 瓶颈、ANN index 膨胀、cache hit 下降；模型端可能出现长尾 ID 过拟合和 norm 方差变大。需按频率 bucket 看收益是否真的来自高维。',
'ANN recall 低怎么调？':'先确认 exact TopK/ground truth 正确，再调 HNSW efSearch/M、IVF nprobe/nlist、PQ code size 等，画 recall-latency-memory 曲线。若调到高成本仍低，可能是量化/索引构建或 metric（IP/cosine/L2）配置不匹配。',
'离线召回高线上无收益为什么？':'可能新增候选与旧路高度重叠、被粗排/精排过滤、只提升不可见 tail、线上特征/index 版本不一致或召回分布与评估不匹配。用 candidate provenance 追踪“新增候选最终走到哪一层”。',
'ANN recall 和业务 Recall@K 有何区别？':'ANN recall 衡量近似索引相对同一 embedding 的 exact TopK 还原程度；业务 Recall@K 衡量候选是否包含真实未来正例/有效内容。ANN recall=100% 也可能业务 recall 很差，因为 embedding 本身可能学错。',
'为什么 ANN recall 很高但端到端 Recall 仍可能低？':'端到端还受 user encoder、候选库过滤、路由 quota、去重、库存/安全 gate 和 label 定义影响。应分解为 model exact recall × index recall × post-filter survival，而不是把所有损失归因索引。',

# Chapter 3
'FM 与 DCN 都做交叉，区别是什么？':'FM 以低秩内积建模主要二阶交叉，参数共享强、适合稀疏；DCN 通过 cross layers 显式构造有界高阶多项式交互。前者归纳偏置更强更轻，后者表达高阶更自然。',
'MLP 为什么也能学交叉？':'多层非线性网络是通用逼近器，理论上能学习 feature interactions；但在高维稀疏推荐中没有显式交叉归纳偏置，可能需要更多样本/参数。DCN/FM 的价值是让目标交互更容易被优化到。',
'如何解释某个交叉是否有效？':'做 grouped ablation、permutation/SHAP（谨慎解释相关特征）并按相关 cohort 看增量；最好还能指出业务机制，例如“夜间×外卖品类”。仅看一个权重大小不能证明因果有效。',
'FM 如何降复杂度？':'利用平方和恒等式，把 Σ_{i<j}<v_i,v_j>x_ix_j 改写成 1/2 Σ_f[(Σ_i v_if x_i)^2-Σ_i(v_if x_i)^2]，从 O(n²d) 到 O(nd)。稀疏输入还能只遍历非零特征。',
'field-aware FM 做了什么？':'FFM 为同一特征针对不同交互 field 使用不同 embedding，例如 user-city 与 item-category 交互可用不同向量，因此表达更强但参数/内存约按 field 数增长。',
'FM 与矩阵分解的关系？':'MF 是 user×item 两类特征的低秩交互；FM 把这一思想推广到任意稀疏特征 pair，并加一阶项。可把 MF 看作 FM 在极简两 field 场景的特例。',
'DeepFM 如何改进？':'常见方向不是无限加 MLP，而是更强交叉（DCN/xDeepFM）、序列兴趣、field-aware interaction、multi-task、better embeddings 和 serving 优化。应先定位瓶颈是交叉能力、序列还是数据，而非直接换“更新模型”。',
'Wide 真的还需要吗？':'当存在稳定业务规则、强记忆型 cross、需要可控修正或快速注入专家知识时仍有价值；否则纯自动交叉可降低维护成本。是否保留要看 wide feature 的独立增量与维护成本。',
'哪些业务规则适合放 Wide？':'少量高置信、可解释、稳定的交叉或规则，如已购买去重、地域×活动、明确资格条件；硬安全/库存约束更应该放模型外 gate，而不是让 wide 学。',
'DeepFM 的二阶项怎么算？':'FM 分支使用同一组 feature embedding 做一阶项和二阶内积，二阶用平方和技巧 O(nd) 计算；deep 分支将这些 embedding 拼接进 MLP。两分支最终 logit 相加再 sigmoid。',
'FM 分支与 DNN 分支梯度会冲突吗？':'会，因为共享 embedding 同时服务低阶内积和高阶 MLP，梯度方向不一定一致。通常共享带来正则化与参数效率，但可通过 separate embeddings、gradient analysis 或分支权重做 ablation。',
'为什么后来又有 DCN？':'DeepFM 的 FM 分支主要二阶，DNN 高阶是隐式学；DCN 希望以参数高效的显式 cross layer直接学习有界高阶交互，提升样本效率和可控性。DCNv2 又进一步解决原 DCN 表达力限制。',
'推导复杂度为什么从 O(n²d) 变成 O(nd)？':'对每个 latent 维 f，把 pairwise 和写成 1/2[(Σ_i v_if x_i)^2-Σ_i(v_if x_i)^2]；每个 f 只需线性遍历 n 个特征。d 个维度因此是 O(nd)。',
'x_i 多数为 0 时还能怎么优化？':'只遍历 active feature/field，embedding lookup 直接取非零 ID；连续 dense feature 单独处理。实际复杂度由非零数 nnz 而不是全 one-hot 维度决定。',
'数值实现中怎样避免构造所有 pair？':'先计算 sum_vx=Σ_i v_i x_i 和 sum_square=Σ_i(v_i x_i)^2，二阶项为 0.5*(sum_vx²-sum_square) 按 latent 维求和；整个过程可用 embedding gather+reduce 完成。',
'FM 二阶项和直接 pairwise dot 的结果如何验证一致？':'在小随机输入上同时实现 naive 双循环和优化公式，用高精度 dtype 比较绝对/相对误差，并做梯度 check。单元测试覆盖 sparse、单非零特征、连续值和重复 field。',
'在特征数翻倍时，计算和内存如何变化？':'优化 FM 计算随 active feature 数近似线性翻倍，而 naive pairwise 约四倍；embedding 表总内存取决于各 field cardinality，不一定随单样本 active 数线性。',
'第 L 层最高能产生几阶交叉？':'经典 CrossNet 从 x0 开始，每加一层可将显式多项式最高阶提高 1，因此 L 层可表示到约 L+1 阶（具体展开包含低阶项）。重点是 bounded-degree 显式交叉而非枚举所有 monomial。',
'DCN 与 FM 的差异？':'FM 主要低秩二阶 pair interaction；DCN 通过层叠 x0 与 xl 的外积式交互形成高阶显式 cross。FM 更轻、更强二阶归纳偏置，DCN 更适合自动高阶组合。',
'为什么 DCN 原版表达力有限？':'原 CrossNet 每层的参数化接近 rank-1/向量式交叉，对复杂 feature interaction 子空间受限。DCNv2 用 full matrix 或 low-rank matrix 提升交叉变换表达力。',
'为什么 web-scale 更偏好可控交叉？':'因为 feature 数巨大，纯 MLP 为学交叉需要更多参数/算力且难解释 ROI；显式结构能用较小容量获得稳定增益，并更容易做 latency/参数预算。可控不等于手工枚举，而是有明确复杂度上界。',
'DCNv2 的 low-rank 什么时候会伤表达能力？':'当有效交叉矩阵本身高秩、不同 feature subspace 需要大量独立方向时，rank 太小会欠拟合。可通过 singular-value/validation sweep、CrossNet-Mix 或部分 full-rank layer 缓解。',
'CrossNet-Mix 与普通 CrossNet 怎么比较？':'CrossNet-Mix 用多个低秩 cross experts 加 gating，使不同样本/交互子空间选择不同交叉模式；普通 CrossNet 单一路径更简单稳定。Mix 提升表达但带来 routing、参数和小算子开销。',
'树模型怎么处理类别特征？':'XGBoost 通常需要 one-hot/target/frequency encoding；LightGBM 支持原生 categorical split（需正确声明类别并注意高 cardinality）。target encoding 必须防 label leakage，按 time/fold 生成。',
'DNN 与 GBDT 如何融合？':'常见是 GBDT 叶节点/统计作为 DNN 特征、GBDT 做 teacher/特征选择，或两模型 score ensemble/stacking。工业上更重要的是增量与 serving 成本，避免重复学习同一信息。',
'时间特征如何周期编码？':'小时/星期等周期变量可用 sin(2πt/T)、cos(2πt/T)，避免 23 点与 0 点在数值上相距很远；也可用 bucket embedding，并加节假日/相对时间等非周期特征。',
'树模型是否需要标准化？':'决策树基于阈值排序，对单调缩放基本不敏感，因此通常不需标准化；但若前处理包含距离、线性模型或混合 pipeline，仍可能需要。异常值/缺失处理比 z-score 更关键。',
'分桶数量怎么选？':'比较分位数/业务阈值下不同 bucket 数的样本 support 与指标，过少丢非线性、过多变稀疏。可同时保留原 continuous 值，让模型在“连续趋势+区间效应”之间选择。',
'动态分布下边界怎么维护？':'固定业务阈值适合语义稳定特征；纯分位数边界则需要版本化重算并保证训练/线上一致。边界变化可能导致 embedding ID 语义漂移，发布时要与模型绑定版本。',
'L2 normalization 对点积检索有什么影响？':'归一化后 dot product 变 cosine，只看方向，移除 norm 对 ranking 的影响；这可稳定 ANN 和防 norm runaway，但可能丢掉模型用 norm 表达的置信度/热门度。需比较 recall 和 calibration。',
'两个强相关特征如何判断谁重要？':'单独 importance 会因共线性互相替代。做 grouped ablation、条件 permutation 或逐一删除后重训，并同时评估读取成本；如果任删一个指标不变，说明信息冗余，可保留更便宜稳定的那个。',
'特征删掉 AUC 不变但线上涨了为什么？':'可能降低了 latency/超时、减少 train-serving skew、提升 calibration/鲁棒性，或 AUC 对该特征影响不敏感。要比较 P99、missing rate、score stability 和线上 cohort，而不是把“离线不变”理解为“无影响”。',
'如何评估实时特征价值？':'离线做 freshness sweep/延迟模拟，比较 T、T-5min、T-1h 的指标；线上 A/B 同时看增益与 feature service P99/成本。用 value-of-freshness = quality gain / serving cost 判断是否值得实时化。',
'怎样设计更贴近线上分布的离线评估？':'使用 time split、point-in-time features、当时可用 item universe、按真实 logging policy 构造候选，并回放线上规则/截断。重要模型再做 shadow replay，验证 score/candidate distribution 与线上一致。',
'如何设计 offline-online correlation dashboard？':'对历史每次模型迭代记录离线 delta（AUC/GAUC/NDCG/Recall、slice）与线上 causal lift（CTR/时长等），按模型类型/场景画散点和回归。若相关性长期低，应更换离线 metric 或构造更贴近线上数据。',
'一次 AUC 提升主要来自重度用户，应该上线吗？':'先判断重度用户是否是业务目标、是否伤害轻度/新用户，以及加权 overall value。用 user-equal 与 traffic-weighted 两套指标和 cohort A/B；不能让高曝光用户在离线 AUC 中无限放大贡献。',

# Chapter 4
'DIN attention 和 Transformer attention 有何区别？':'DIN 是 candidate-conditioned local activation：target 与每条历史匹配后聚合；Transformer self-attention 主要建模历史 token 之间关系并通常使用 QKᵀ/softmax。DIN 更直接回答“哪些历史与当前候选相关”，二者可组合。',
'长历史时 DIN 为什么贵？':'每个 candidate 都要与 L 条历史做 target-aware interaction，精排 C 个候选成本近似 O(C·L·d)。当 C、L 同时大时应缓存 candidate-independent 表示、先筛历史或使用 SIM/长序列架构。',
'DIN 是否能建模兴趣演化？':'它主要对历史做 target-aware 加权，没有显式状态转移/时间演化机制；时间特征可加入 activation，但仍不同于 DIEN 的 interest extractor/evolution。短序列下 DIN 仍可能性价比更高。',
'如何加入时间特征？':'把 time gap、行为发生时刻、周期特征编码为 bucket embedding/连续 bias，与 behavior-target interaction 一起输入；也可在 attention logit 加时间衰减。训练/线上都必须使用预测时刻可见时间。',
'Cross-Attention 与 DIN 更像吗？':'是，结构上 candidate query 对 history keys/values 的 cross-attention 与 DIN 的 target-aware aggregation 更接近；区别在打分函数、多头、归一化和投影。DIN 可看作面向推荐的较轻量条件化 attention。',
'什么时候只用 DIN 更划算？':'历史长度中等、候选数可控、target-conditioned 兴趣是主要增益而复杂时序依赖不强时。若 Transformer/DIEN 只带极小增量却显著增加 P99，DIN 常是更好 Pareto 点。',
'DIEN 如何改进？':'DIEN 用 GRU 从行为提取 latent interest，并用 auxiliary next-behavior loss 给中间状态监督，再通过 target-aware interest evolution（AIGRU/AGRU/AUGRU）建模与候选相关的状态变化。',
'SIM 如何降低长序列成本？':'GSU 先用廉价 search 从 lifelong history 取 target-related 小集合，ESU 再复杂建模，把 O(全历史×候选) 变成“检索 + 小序列交互”。代价是 GSU 召回成为不可恢复瓶颈。',
'DIN 为什么仍然常用？':'结构简单、target-aware 信号强、易与现有 CTR 特征体系结合，且中短序列时质量/成本非常有竞争力。工业系统不会因为有更新论文就自动淘汰稳定高 ROI 模块。',
'辅助 loss 的正负样本怎么构造？':'DIEN 常让 h_t 预测真实下一行为 e_{t+1} 为正例，采样未发生行为为负例，用二分类/对比 loss；负样本策略同样需防 false negative 和热门偏差。',
'AUGRU 为什么优于 AGRU？':'AGRU 用 attention score 直接替换 update gate，可能丢掉 GRU 自身学习的更新强度；AUGRU 用 attention 缩放原 update gate，保留状态动态与 target relevance 两个信号，表达更细。',
'α 怎么选？':'若指 auxiliary loss 权重 α，应做 log-scale sweep，观察主任务指标与 auxiliary accuracy/gradient norm；α 太小监督无效，太大模型会偏向 next-behavior 目标。最终以主任务线上/离线 Pareto 决策。',
'如果序列不是严格时间行为怎么办？':'先定义事件因果/可见顺序：并发事件可按 session/bucket 聚合，时间戳噪声可用 coarse time bin；如果本质是无序集合，则不应强行 RNN，改用 set/attention pooling 更合理。',
'能否用 contrastive auxiliary objective？':'可以，让当前兴趣状态拉近后续真实行为、推远采样负例，类似 supervised contrastive/InfoNCE。需要控制负例语义和 loss weight，并验证它是否改善主 CTR/排序而非只改善 representation metric。',
'AIGRU 是怎么做的？':'先计算 target-aware attention a_t，再把输入 embedding 缩放为 a_t·e_t 后送入普通 GRU；它在输入侧过滤无关行为。相比 AGRU/AUGRU，它不直接修改 GRU update gate。',
'为什么标量 attention 可能限制表达？':'一个标量只表示整条行为“相关/不相关”，无法在不同 latent channel 上选择性激活。可用 multi-head/vector-wise gating 提升表达，但成本更高，也更容易过拟合。',
'重复次数应该作为 feature 还是保留多 token？':'取决于重复的语义和时间结构：短时间系统重试应去重；真实重复消费可保留次数/频率特征，若重复间隔本身有信息则保留 token。可做 dedup-window sweep 验证。',
'实时序列和离线序列如何一致？':'统一 event schema/sessionization/dedup 代码，训练使用 event-time point-in-time join；线上定期 dump 序列并离线 replay 对比 token、顺序和时间特征。任何规则版本与模型一起发布。',
'HSTU 试图解决的又是什么问题？':'它针对高基数、异构、非平稳的推荐行为序列重新设计序列 transducer，并强调长序列效率与 compute scaling；目标不是单纯降低一个 attention kernel，而是让推荐模型能更像 foundation model 一样随规模获益。',
'序列从 1k 增到 10k 时应该先优化哪个瓶颈？':'先 profile：attention pair/IO、embedding lookup、内存、candidate interaction 哪个主导；多数情况下先问“后 9k 行为有多少增量信息”，尝试 search-first/压缩/分层，再考虑 kernel 优化。',
'长序列收益只集中在高活用户时怎么上线？':'做 cohort routing：高活跃/长历史用户走长序列模型，低活用户保持轻模型；在线按 history length/uncertainty gating，避免让所有流量承担成本。整体 ROI 用加权 uplift-cost 计算。',
'如何设置 M？':'SIM 中 M 是 GSU 保留历史数，做 M sweep 看 GSU recall、ESU quality 和 P99；通常选择边际 quality gain 开始变平的点，并可按用户历史长度动态 M。',
'SIM 与 RAG 有什么结构类比？':'二者都是“先检索相关上下文，再用更强模型精处理”：GSU 类似 retriever、ESU 类似 reader/generator。不同在 SIM 检索对象是用户自身行为，目标与训练数据机制也不同。',
'SIM 与 long-sequence Transformer 如何组合？':'可用 GSU 先筛小集合送 Transformer，或 Transformer/HSTU 产全局状态、SIM 另取 target-specific memory 再融合。组合是否值钱要看 GSU 截断与 Transformer 成本的 Pareto。',
'用户序列中 CLS token 有何作用？':'作为聚合 token 通过 attention 汇总序列，便于得到固定维 user state；但推荐 target-aware 任务未必需要单一 CLS，可用最后状态、mean pooling、多兴趣 tokens 或 candidate cross-attention。',
'为什么线上 micro-batch 场景更偏向 LayerNorm？':'LayerNorm 不依赖 batch 统计，单请求或小 batch 的输出与训练 batch 大小更一致；BatchNorm 的 running stats 在非平稳推荐流量下可能失配。',
'变长序列会如何影响 BatchNorm 统计？':'padding、不同历史长度和 token 分布会让 batch/时间维统计受组成影响，如果 mask/统计维处理不当尤其严重。LN/RMSNorm 在 hidden 维归一更自然。',
'推荐模型里 BatchNorm 什么时候仍然有用？':'稳定大 batch 的 dense MLP、连续特征 tower 或离线训练与线上 batch 统计可可靠匹配时仍可用。选择依据是张量维度、batch 稳定性和 serving 行为。',

# Chapter 5
'Shared Bottom 为什么会失败？':'所有任务强制共享同一 representation，若梯度冲突或任务相关性低，一个任务更新会破坏另一个。可看共享层 gradient cosine、per-task ablation 和任务条件分布判断是否 negative transfer。',
'线上分数如何融合？':'先对各 task score 做 calibration，再按业务 utility/约束融合，如 α·pCTR+β·E[watch]-λ·negative；也可训练融合层。模型训练 loss 权重与线上 score weight 不必相同。',
'哪些任务适合 Shared Bottom？':'标签/输入机制相似、梯度方向大体一致、数据规模不足以各训一套的任务。它应作为强 baseline；若已经稳定且无跷跷板，不必为了架构新颖换 MMoE。',
'梯度冲突如何直接处理？':'可用 PCGrad、CAGrad、GradNorm 等在共享参数梯度层面做投影/平衡，或增加 task-specific capacity。先测 gradient cosine 与任务表现，避免在没有冲突证据时增加复杂度。',
'MMoE 的缺点是什么？':'所有 experts 仍是共享池，任务特异隔离有限；gate 可能 collapse，expert 数增加带来计算/小算子/可观测性成本。PLE 通过 shared/task-specific experts 更显式地控制共享。',
'能否做 task-specific experts？':'可以，这正是 PLE 等结构的重要方向：每个任务有私有 experts，另有 shared experts，再用 gate 融合。代价是参数和 serving 成本上升，需要证明负迁移确实存在。',
'PLE 为什么要进一步拆 experts？':'MMoE 允许 task-specific gate，但 expert 本身全共享；若任务冲突，仍可能把无关信息带入。PLE 将共享和私有 experts 分开，并逐层提取，减少 unwanted sharing。',
'如何判断是 negative transfer 还是业务真实冲突？':'先比较 separate-task models：若各自单训都能好，但共享后一个涨一个跌，更像 negative transfer；若即使独立模型上线也呈现 CTR-留存互斥，可能是业务目标 Pareto 冲突。',
'上线决策怎么处理 Pareto frontier？':'把主/次指标的候选方案画成 Pareto set，淘汰被全面支配方案，再按业务价值和 guardrail 选点。不要用一个任意加权和掩盖明显的指标牺牲。',
'为什么 task-specific expert 能缓解负迁移？':'它给每个任务保留不会被其他任务梯度直接争夺的容量，同时 shared experts 继续复用共性。关键是 gate 能学到“哪些信息共享、哪些私有”，而不是完全隔离。',
'冻结 head 为什么仍可能掉？':'head 冻结但 shared bottom 仍被其他任务更新，输入表示分布变化会让固定 head 失配。因此需要冻结部分 shared 层、降低相关 LR、stop-gradient 或维护 replay/regularization。',
'如何做 per-task LR？':'对 task head 使用独立 optimizer group/LR；共享参数本身接收所有任务梯度，需配合 loss weight/gradient scaling。动态 LR 应看每任务 validation 与 gradient norm，而不是只看训练 loss。',
'ESMM 怎么避免 SSB？':'它不只在 clicked samples 上训练 CVR，而是在 entire impression space 同时监督 CTR 和 CTCVR，并通过 pCTCVR=pCTR·pCVR 约束共享表示，使 CVR 学习不局限于点击子空间。',
'CVR 与 CTCVR 有什么关系？':'pCVR=P(conversion|click, impression)，pCTCVR=P(click∩conversion|impression)=pCTR·pCVR。CTCVR 在所有曝光上都有标签，因此更适合 entire-space supervision。',
'为什么 CTCVR 比 CVR 更容易在 entire space 上监督？':'每个曝光都知道最终是否“点击且转化”，所以 CTCVR 标签全空间可观测；而未点击样本的 post-click CVR 是反事实不可观测。',
'ESMM 输出 CVR 如何做校准？':'应按 pCTR/pCTCVR/pCVR 分别画 reliability，尤其检查低 pCTR 区间的比值放大。可用 validation 上 Platt/isotonic/temperature，但要保持 pCTCVR≈pCTR·pCVR 的一致性。',
'ESCM² 的反事实思想是什么？':'核心是把曝光→点击→转化链中的选择偏差显式视为因果/反事实问题，用 propensity/因果约束校正“只在点击后观察 CVR”的机制，而不只靠 ESMM 的乘积结构。具体实现应以论文公式为准。',
'为什么除法式 pCVR 容易放大误差？':'pCVR≈pCTCVR/pCTR，当 pCTR 很小时，分母的微小绝对误差会导致较大相对误差；两模型误差还可能相关。需要 clipping、joint calibration 或避免直接数值除法解释。',
'如何比较 ESMM、ESCM² 与普通 CVR baseline？':'统一 point-in-time 数据与候选，按全曝光/点击子空间、新老用户/品类评估 CVR calibration、CTCVR ranking 和线上 GMV/转化；同时比较复杂度和 propensity 估计稳定性。',
'如果 propensity 本身估计不准怎么办？':'做 overlap/weight diagnostics、clipping/SNIPS，并采用 doubly robust 结合 outcome model；更重要的是通过受控随机探索改善 propensity 可识别性。错误 propensity 下“理论无偏”不再成立。',
'时长和 CTR 如何做多任务？':'共享 user-item representation，分别用 BCE 预测 CTR、用回归/分桶/分布头预测 watch time，再通过 MMoE/PLE 控制冲突。线上需校准后按业务 utility 融合，并把负反馈/留存作为 guardrail。',
'分类分桶、回归和分布建模怎么选？':'若重尾且只需稳定排序，分桶分类常更稳；需要连续期望可用 log/Huber 回归；需要尾部/不确定性可用 mixture/quantile。用离线 calibration+ranking 与线上 utility 同时选。',
'时长模型上线要看哪些 guardrail？':'至少看 CTR/有效播放、短跳出、负反馈、视频长度分布、session depth、留存和 P99。防止模型通过偏长内容、自动播放或低质量拖时“刷”watch time。',

# Chapter 6
'BCE 与 focal loss 区别？':'BCE 对所有样本按对数似然优化；focal loss 乘 (1-p_t)^γ 下调易样本、强调难样本。极度不平衡/易负例很多时有用，但会改变概率校准且可能放大噪声 hard examples。',
'为什么 AUC 涨而 logloss 变差？':'AUC 只关心排序，logloss 关心概率值。模型可能把正负顺序排得更好，但预测过度自信/校准变差；多目标融合或收益估计场景应同时看 ranking 与 calibration。',
'为什么 pointwise 也能得到好排序？':'如果 BCE 学到的概率/score 与真实相关性单调，按 score 排序自然也好；大规模 pointwise 数据稳定、易校准。pair/listwise 的优势主要在更直接对齐相对顺序，而非必然胜出。',
'Pairwise 如何做负采样？':'对每个正 item 从曝光未点击、随机或 hard pool 取负例，构造 (u,i+,i-)；采样分布决定训练边界。应混合难度、防 false negative，并记录 propensity/source。',
'为什么线上 CTR 很低但 AUC 仍高？':'CTR 是正例基率，AUC 是正负相对排序概率，二者维度不同。1% CTR 数据也可有 0.8 AUC；但低基率下 precision/PR-AUC 和 calibration 更值得补充。',
'GAUC 与 request-level AUC 有何区别？':'GAUC 通常先在 user/group 内算 AUC再加权；request-level AUC把每次请求内候选作为竞争集合，更贴近单次排序。应让 group 定义对应线上决策粒度。',
'权重变化会怎样影响模型选择？':'曝光加权 GAUC 更重度用户导向，用户等权更关注平均用户；改变权重可能改变模型排名。应同时报告 traffic-weighted 与 user-equal，明确业务价值函数。',
'多正例用户怎么计算？':'Recall@K 分母是该用户测试窗口内相关 item 总数，TopK 命中几个就计几个；若使用 leave-one-out 则退化为单正例。要明确 relevance window 和同一 item 去重规则。',
'跨设备 user identity 不一致会怎样污染实验？':'同一人可能在手机进入 treatment、平板进入 control，使处理效应互相稀释并违反稳定分组。应做 identity stitching、device→user sticky mapping，至少估计 multi-device cohort 的 contamination rate。',
'如何判断 clickbait？':'看点击后质量：短停留/快速返回、完播、负反馈、session continuation 与长期留存，并按标题/封面类型 slice。CTR 上涨同时 post-click quality 系统性下降是强信号。',
'如果时长短期掉但次留涨呢？':'说明时长可能不是最终目标或存在“更高效消费”。按预注册 primary/guardrail 决策，并延长观察确认次留提升稳定；若长期价值更高，可接受受控短期时长下降。',

# Chapter 7
'哪个 bias 对 CTR 影响最大？':'没有统一答案，position/exposure 往往最直接，但业务场景不同。应通过随机化/propensity、位置 slice、热门度和 policy replay 量化每类 bias 对估计和模型选择的敏感度。',
'去偏会不会降低短期指标？':'可能，因为旧策略已围绕当前曝光分布优化，去偏/探索会牺牲短期 CTR 换更真实学习和长期覆盖。决策要看长期效用、估计方差和供给生态，且用小流量控制风险。',
'线上不能大规模随机怎么办？':'做小比例安全探索、局部 position swap、interleaving，或结合 click model/自然实验估 propensity；再用 IPS/DR。没有任何 overlap 时，纯观察数据无法可靠识别从未展示动作的反事实。',
'position bias 与 presentation bias 区别？':'position bias 是排名位置导致 examine 概率不同；presentation bias 来自卡片样式、图片、字体、自动播放等展示方式。二者可同时存在，实验应分别随机化或作为结构化因子建模。',
'focal loss 何时不适合？':'当概率 calibration 很重要、hard examples 含大量 label noise、或类别不平衡并非主要瓶颈时。γ 过大会让少量噪声样本主导，应与 weighted BCE/采样+校准比较。',
'召回与精排的负采样是否应相同？':'通常不应完全相同。召回需要覆盖整个 item space 和 ANN 竞争边界，精排更应模拟“已被召回/曝光的难候选”；两者 sampling distribution 应对应各自线上决策集合。',
'如何做动态 hard negative mining？':'周期性用最新模型/teacher 在真实候选库检索 top-scored non-positive，按模型版本写入 pool；训练混入 random/曝光负例。控制刷新频率和 false negative，避免模型错误闭环。',
'为什么 batch inference 会增大等待？':'为了凑 batch，早到请求会排队，吞吐变高但 queueing latency 上升。在线要用 dynamic batching/最大等待窗口，在 GPU utilization 与 P99 之间选 Pareto 点。',
'热 ID/冷 ID 的缓存与存储如何分层？':'高频 embedding 放本地 HBM/DRAM cache，温数据在主机/近端 KV，冷数据远端存储；按访问频率动态晋升/淘汰。要监控 cache hit、热点 shard 和一致性。',
'分布式 embedding sharding 如何保证版本一致？':'参数/表使用 snapshot/version epoch，发布时各 shard 完成加载后再原子切全局 routing；读请求携带版本或通过双 buffer 防混读。增量更新还需 checkpoint/offset 对齐。',

# Chapter 8
'如果线上收益只集中在一个 cohort，你怎么决策？':'先确认 cohort 预先定义且样本量足，估计 overall weighted value 与其他 cohort guardrail。若机制合理，可做 cohort-targeted rollout；不要把事后挖出的偶然 subgroup 当确定收益。',
'长尾 Item 是否都值得曝光？':'不。长尾只是历史曝光少，不等于高质量；先过质量/相关性/safety gate，再给不确定但潜在优质 item 探索机会。目标是纠正机会不足，不是均匀分配流量。',
'用户只喜欢单一类目怎么办？':'多样性强度应个性化：兴趣熵低的用户保持主题相关性，只做类目内部作者/风格/新颖性多样化；同时留少量相邻兴趣探索，避免强行跨类目。',
'如何为不同用户动态调多样性强度？':'用兴趣熵、历史跳出/接受新主题、session 深度、新老用户状态作为输入预测 λ/constraint；设上下界并在线 A/B。可把多样性看成 policy 而不是全局常数。',
'探索流量会不会伤害短期 CTR？':'通常会有机会成本，所以需要控制 regret：只在相关性/质量下界内探索，按 uncertainty 动态分配，小流量起步。长期收益来自更快学习用户/内容和减少反馈闭环。',
'保量 quota 应该固定还是动态？':'更推荐动态：随 item age、有效曝光数、后验质量、不确定性和供给拥挤度变化。固定 quota 简单但会对低质内容浪费流量、对高潜内容又可能不足。',
'新内容策略如何评估长期生态收益？':'除新 item CTR/消费外，看作者/供给留存、优质新内容发现率、曝光集中度、用户长期满意度和作弊率；最好保留长期 holdout，避免只看探索期即时反馈。',

# Chapter 9
'HSTU 与标准 attention 的计算/归一化思想有何不同？':'安全的面试表述是：HSTU 并非直接照搬语言 Transformer 的标准 attention block，而是针对推荐行为序列重新设计注意力/门控与相对时序偏置，并强调高效长序列实现。具体算子细节应以 ICML 2024 原论文/官方实现为准；不要在没把公式记准时臆造“只是去掉 softmax”。',
'二者如何蒸馏？':'让生成式/更强 cross model teacher 对 user-item 产 soft score、pair preference 或 semantic state，双塔 student 用 KL/contrastive/ranking loss拟合；还可用 teacher 挖 hard negatives。必须保持 student 的分离编码与 ANN 可索引约束。',
'新 item 的 semantic ID 需要重建全局 codebook 吗？':'通常不希望。固定 codebook 时，新 item 直接经过 encoder/quantizer 得 code；若分布漂移严重再周期重训 codebook，并做版本化迁移。动态重建会导致历史 token 语义变化，成本很高。',
'为什么 self-attention 在 ranking token 数上未必划算？':'ranking 的 token 数可能不大，但 QPS 极高，标准 attention 的 QKV 投影、softmax、kernel launch 和小矩阵开销会在每请求重复；若 feature interaction 更适合简单 mixing，硬件友好架构可能用更高 MFU 扩大模型而不增延迟。',
'未来推荐 foundation model 的训练数据是什么？':'核心是大规模时间有序行为序列：曝光、点击、观看、互动、购买等 action token，加 item 内容/多模态语义、上下文和时间；训练需严格 point-in-time、去偏和隐私治理。相比语言语料，它更非平稳、反馈闭环更强。',
}

pattern=re.compile(r'(### 追问 \d+：(?P<q>.+?)\n\n)(?P<a>.*?)(?=\n### 追问 \d+：|\n## 自测清单)',re.S)
changed=0
for p in ROOT.glob('docs/questions/*/q*.md'):
    t=p.read_text(encoding='utf-8')
    def repl(m):
        nonlocal_dummy=None
        q=m.group('q').strip()
        if q in D:
            return m.group(1)+D[q].strip()+'\n'
        return m.group(0)
    new=pattern.sub(repl,t)
    if new!=t:
        p.write_text(new,encoding='utf-8'); changed+=1
print('polished files',changed,'direct answers',len(D))
